### ISSUE TITLE
fiber link : big differences between browsers

### ISSUE THREAD

**Issue by Alsemevad** [nesk/network.js#30] opened 2015-04-23 07:24 UTC
Hi
I have a 100MB fiber optic link. 

Firefox : 
=> Upload : 79.079 MBps
=> Download : 98.210 MBps

Google Chrome : 
=> Upload : 79.953 MBps.
=> Download : 50.461 MBps.

On Google Chrome, the download result it's always around 50MB.
It's a interne limit of Chrome ? (Same problem with Chromium).

**Comment by nesk** [comment] 2015-07-29 20:02
Unable to reproduce, closing. I don't have any fiber optic link to try this. Feel free to make a pull request if you want to see this fixed.

**Closed by nesk** 2015-07-29 20:02 UTC
